# Generated by Django 4.0.5 on 2022-06-22 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ninja',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.persona')),
                ('chakra_max', models.IntegerField(default=0)),
                ('sobrenombre', models.CharField(default='', max_length=50)),
            ],
            bases=('api.persona',),
        ),
    ]
