# Generated by Django 4.0.5 on 2022-06-23 14:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ninja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
