# Generated by Django 4.0.5 on 2022-06-23 15:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_persona_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='id',
            field=models.UUIDField(default=uuid.UUID('42a7a544-2e69-4abb-a13c-8c9bcfda149e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
