# Generated by Django 4.0.5 on 2022-06-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_persona_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='id',
            field=models.UUIDField(default='6b16594e-cbc9-4428-b9d9-88a2a5336b2b', editable=False, primary_key=True, serialize=False),
        ),
    ]
