# Generated by Django 4.0.5 on 2022-06-23 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_persona_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='id',
            field=models.IntegerField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
